// DevTeam Hub - main.js
// DO NOT EDIT THIS FILE as part of the exercises.
// It handles rendering the project board from data/projects.js

document.addEventListener("DOMContentLoaded", function () {
  const list = document.getElementById("project-list");

  if (!list || typeof projects === "undefined") return;

  projects.forEach(function (p) {
    const statusColour =
      p.status === "complete"
        ? "bg-green-900 text-green-300"
        : p.status === "in-progress"
          ? "bg-indigo-900 text-indigo-300"
          : "bg-gray-700 text-gray-400";

    list.innerHTML += `
      <div class="bg-gray-800 rounded-xl p-6 border border-gray-700 team-card">
        <div class="flex items-center justify-between mb-2">
          <span class="font-semibold text-white">${p.project}</span>
          <span class="text-xs px-2 py-1 rounded-full ${statusColour}">${p.status}</span>
        </div>
        <p class="text-sm text-gray-400 mb-3">${p.description}</p>
        <p class="text-xs text-gray-500">
          by ${p.member} &mdash;
          <a href="${p.github}" target="_blank" class="text-indigo-400 hover:underline">GitHub</a>
        </p>
      </div>
    `;
  });
});
